### ISSUE TITLE
Shortcuts 

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss-plugin-suggestion-box#2]
I'm moving the discussion from [#645](https://github.com/postcss/postcss/issues/645) to here. 

David added a couple of cool suggestions from http://davidtheclark.github.io/scut/

> - HiDPI breakpoint
> - hide visually
> - image replacement
> - triangle
> - center absolutely
> - center block
> - center transform
> - clearfix
> - ratio-box
> - sticky-footer, fixed height
> - sticky-footer, fluid height
> - vertical center, inline-block method
> - vertical center, table display method
> - vertical center, transform method
> - hanging indent
> - indented paragraphs
> - truncate

**Comment by ismamz** [comment]
I started to do this.
Is postcss-shortcuts a good name?

**Comment by jonathantneal** [comment]
@ismamz, nice! I am working on _hide visually_, but trying to get it close to what could actually be spec, in response to [this concern](#issuecomment-215315075). We have some of the other ones covered, like clearfix, ratio-box, etc. I will find the links later.

**Comment by marcustisater** [comment]
The best thing would be to create individual plugins and then bundle those into a pack that would be called postcss-shortcuts, sort of like @jonathantneal [postcss-precss](https://github.com/jonathantneal/precss). That's best practice for the ecosystem.

**Comment by ai** [comment]
Wait-wait. The whole point of that issue, was to create good way to add these shortcuts.

Non-standard properties are bad. And it is one of the biggest problem of PostCSS. So, we should find some way to explicit show source of this magic.

**Comment by ismamz** [comment]
@ai Ok. Correct me if I'm wrong. The idea is to avoid non-standard properties and use a new kind of rule (`@hack ...` was you suggestion) for utilities, shortcuts, etc. In this new plugin we collect all those "hacks" with a clear documentation.

**Comment by ai** [comment]
Yeap, it was the origin idea

**Comment by ai** [comment]
Also maybe `@hack` name is not so good? What do you think?

**Comment by ismamz** [comment]
I don't know, but maybe `@hack` is not the best name. We should use something short. `@use` is already taken, but something like that.

Do you think that all these "hacks" should be created in a individual sub-plugin?
For example, (I assume that `shortcuts` is the plugin name), `postcss-shortcuts`, and `postcss-shortcuts-subplugin`? Or keep all inside the plugin?

**Comment by marcustisater** [comment]
I don't think `@hack` is a appreciated name, maybe `@shortcut` or the name of the plugin to associate it in a better way. 

> Do you think that all these "hacks" should be created in a individual sub-plugin?

That is a really good question @ismamz. If everything is inside the @use rule, I think we can keep it in the same plugin rather then splitting it into several ones but then again that depends, I am not really sure how to translate the plugin guidelines for this particular example. @ai thoughts?

**Comment by ai** [comment]
`@add` could be good name. It is short abd semantic.

But maybe we should provide some kind of mixins libraries for postcss-mixin?

**Comment by ai** [comment]
Like postcss-mixins-pack. We can provide some API: you will add postcss-mixins-pack as a PostCSS plugin before postcss-mixins and it will automatically insert paths to postcss-mixins

**Comment by marcustisater** [comment]
That's a better idea, this could work as a mixin library and it could be a add-on instead of completely rewriting it. 

Just to clarify if I understand this correctly; we write a separate "add-on" plugin to postcss-mixins which would have all kinds of "hacks/shortcuts" with API doc to it.

**Comment by ismamz** [comment]
But, postcss-mixins-pack would be like [Bourbon](http://bourbon.io/) or [Scut](https://davidtheclark.github.io/scut/)? A mixins library written in CSS for example?

I think that the idea of create a kind of mixins library included in a postcss plugin is a good idea. For example: _postcss-utilities_ and you can use `@add` to call each "utility". Then, we could create a very detailed documentation and everybody can contribute on it to mantain a single PostCSS utilities library. Do you think that it's complicated?

We need to find a term:
- shortcut
- mixin
- feature
- utility
- pattern
- tool

Which is the best?

**Comment by ai** [comment]
@ismamz do you like to use `@mixin clearfix` instead of `@add clearfix` (`add` is not clear, what plugin added this at-rule) or `@util clearfix`

**Comment by ismamz** [comment]
Keep `@mixin` for mixins, and maybe `@util` is better.

**Comment by ai** [comment]
Yeap. At least with `@util` we will not force users to add `postcss-mixins` and to put it only before this plugin.

Also `@util` is shorter.

**Comment by marcustisater** [comment]
Sounds good, @ismamz let me know if you need any help. I'm free for os project.

**Comment by ismamz** [comment]
@marcustisater maybe we could start creating a list of utilities.

**Comment by marcustisater** [comment]
Sure, I can setup [repo](https://github.com/marcustisater/postcss-utilities) and we can go from there. We can migrate later.

**Comment by marcustisater** [comment]
https://github.com/ismamz/postcss-utilities
