### ISSUE TITLE
Debugging tool

### ISSUE THREAD

**Issue by andywer** [postcss/postcss-plugin-suggestion-box#3]
I am currently writing a debugging plugin for PostCSS. Wanted to check if someone else might be interested in such a thing :)

I just started it, so there is not much to show yet. Here is a screenshot of what its output currently looks like:

<img width="570" alt="bildschirmfoto 2016-04-29 um 19 22 48" src="https://cloud.githubusercontent.com/assets/1842462/14923913/3d17a5ca-0e40-11e6-8329-3925c1a56a79.png">

**Comment by ai** [comment]
Awesome!

**Comment by ai** [comment]
Also you should add a highlight (but plugin is still awesome)

**Comment by ai** [comment]
Don't forget to ping me, when you finish. It is very important plugin for ecosystem.

**Comment by andywer** [comment]
Sure. Yeah, I also thought about a colored diff using https://www.npmjs.com/package/diff. Shouldn't be hard.

But I am still trying to figure out how to provide all necessary data and still don't make the developer drown in information. `console.log` is probably not ideal. Maybe it's best to create some HTML output and automatically open it in the browser when it's done...

New ideas are definitely welcome ;)

**Comment by ben-eb** [comment]
I think a HTML output is much better, especially given that most CSS files are likely to have a lot of rules in them. And there's plugins like cssnano which contain many processors in, so even with one or two rules you get 20 different console logs. 😄

**Comment by marcustisater** [comment]
I agree with @ben-eb. HTML output would be more ideal for these types of logging, but it's going to be a challenge of how to present it for the end user.

Let us know if you need any help, we don't bite 😄 I'm not much for coding but I'd love to help you with documentation or UX.

**Comment by andywer** [comment]
Good point. Thanks, guys.

I think what makes it a little more tricky is that it might be used in a browser (if you use the JSPM loader for instance), too. But I think Node-only is fine for now...

Going to hack a little more, then release some alpha version early! Message received, @marcustisater :)

**Comment by andywer** [comment]
It has been some time and I had a lot of other stuff to do, but finally here it is: A first release! ;)

Have a look at https://github.com/andywer/postcss-debug. Contributions are welcome!

**Comment by ai** [comment]
@andywer looks awesome!

**Comment by ai** [comment]
I will promote it in PostCSS twitter account. In best days on next week (best days for SMM is Wednesday and Friday).

**Comment by ai** [comment]
@andywer But could your write a tweet about this project. First I will RT you

**Comment by marcustisater** [comment]
Awesome, looks great. 👍

**Comment by ai** [comment]
@andywer don’t afraid all that issues that I created :). I am very excited about your project, it is very useful for community. So with all that energy I thought how to do it ideal :). I understand that most of issues is long work for next major released :). Great work.

**Comment by andywer** [comment]
Thanks, @ai! I appreciate the feedback :)
