### ISSUE TITLE
postcss-fixes - pack for browser support workarounds

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss-plugin-suggestion-box#5]
It would be nice with a pack of individual PostCSS plugins to resolve known browser support issues, like [postcss-flexbugs-fixes](https://github.com/luisrudge/postcss-flexbugs-fixes) or [pixrem](https://github.com/robwierzbowski/node-pixrem). We are **not** talking about vendor prefixing. 

Up for grabs, see [tweet](https://twitter.com/andreysitnik/status/730140537790078976) from @ai. Feel free to drop a line if you know any similar plugins that has browser issues workarounds/polyfills/fallback.

**Comment by MattDiMu** [comment]
https://github.com/MattDiMu/postcss-fixes
https://www.npmjs.com/package/postcss-fixes

I plan on adding more plugins in the future :)

**Comment by marcustisater** [comment]
Great, I'll have a look to give you some feedback, then we can promote it.
