### ISSUE TITLE
Module for generating contrastive font color based on background color

### ISSUE THREAD

**Issue by anshul-shukla** [postcss/postcss-plugin-suggestion-box#9]
Idea is programmatically determine if the background of a selector is "light" or "dark" ; accordingly put font-color , black and white respectively.

**Comment by ai** [comment]
@anshul-shukla what do you think about https://www.npmjs.com/package/postcss-contrast ?

**Comment by anshul-shukla** [comment]
@ai oops! already there. Yes this is exactly same.

**Comment by mhewson** [comment]
would be great if the default color values could be unique per selector
